### ISSUE TITLE
Edit Jaeha's index.html file

### ISSUE THREAD

**Issue by jaehafe** [gorocat/introduce#3]
## 설명

이재하 자기소개 index.html을 좀 더 자세히 작성

## Tasks

- [x] 취미
- [x] 좋아하는 음식
- [x] 좋아하는 음악

## Reference
[mdn about html](https://developer.mozilla.org/ko/docs/Learn/HTML/Introduction_to_HTML/Getting_started)

**Comment by gygy7151** [comment]
수고 많으셨습니당!
